classDiagram
    class conversation {
    	-int id
	-string name
    }
    class message {
	-int id
        -string data
        -string media_type
        -dateTime timestamp
        -string signature
        -int sender_id
    }
    class user {
    	-int id
	-string email
	-string display_name
	-int[] password
	-int[] public_key
    }
